{
 "title": "Eaton UPS Monitoring",
 "description": "Eaton UPS Monitoring ",
 "tags": [
  "UPS",
  "Eaton"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "eatonmodel",
    "label": "Eaton",
    "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] == \"192.168.100.91\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsIdentModel\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
   },
   {
    "name": "eatonhostname",
    "label": "Hostname",
    "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] != \"\")\r\n  |> keep(columns: [\"agent_host\"])\r\n  |> distinct(column: \"agent_host\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Eaton UPS Overview -  $eatonhostname",
   "type": "stat",
   "description": "This panel shows basic information about your Eaton UPS Device",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "repeat": "eatonhostname",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsIdentModel\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> keep(columns: [\"_value\"])\r\n  |> distinct(column: \"_value\")\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"])"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsIdentSoftwareVersion\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> keep(columns: [\"_value\"])\r\n  |> distinct(column: \"_value\")\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"]) "
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsBatCapacity\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> keep(columns: [\"_value\"])\r\n  |> distinct(column: \"_value\")\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"]) "
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsTestBatteryStatus\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> keep(columns: [\"_value\"])\r\n  |> distinct(column: \"_value\")\r\n  |> group() \r\n  |> last() \r\n  |> keep(columns: [\"_value\"])"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsBatTimeRemaining\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 60.0 }))\r\n  |> distinct()\r\n  |> yield(name: \"mean_in_minutes\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsBatteryAbmStatus\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> distinct()\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsAlarms\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> aggregateWindow(every: ${interval}, fn: mean)\r\n  |> distinct(column: \"_value\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "UPS Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Output Watts - $eatonhostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsOutputWatts\")\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> aggregateWindow(every: ${interval}, fn: mean)"
    }
   ]
  },
  {
   "title": "Output Load - $eatonhostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "    from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsOutputLoad\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Voltage - $eatonhostname",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsInputVoltage\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "  from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsOutputVoltage\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Input & Output Frequency - $eatonhostname",
   "type": "timeseries",
   "description": "Input & Output Frequency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rotkhz" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsInputFrequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean_in_kilohertz\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"agent_host\"] =~ /${eatonhostname:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xupsInputFrequency\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"snmp.ups\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value / 10.0 }))\r\n  |> yield(name: \"mean_in_kilohertz\")"
    }
   ]
  }
 ]
}